#!/usr/bin/env python3
import argparse
import os.path as op
from markdown2html import Markdown2Html


def get_args():
    '''
    获取命令参数
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--style', help='指定要使用的 css 样式，css文件路径')
    parser.add_argument('-o', '--outdir', help='指定 html 文件输出目录')
    parser.add_argument('infiles', nargs='+', help='指定要转换的 markdown 文件，可以指定多个')
    return parser.parse_args()


if __name__ == '__main__':
    args = get_args()
    m2h = Markdown2Html()
    if args.style:
        m2h.setStyle(args.style)
    for mdfile in args.infiles:
        if args.outdir:
            filename = op.splitext(op.basename(mdfile))[0] + '.html'
            outfile = op.join(args.outdir, filename)
            count = 1
            while op.exists(outfile):
                filename = op.splitext(op.basename(mdfile))[0] + f'_{count}.html'
                outfile = op.join(args.outdir, filename)
                count += 1
        else:
            outfile = op.splitext(mdfile)[0] + '.html'
        m2h.convert(mdfile, outfile=outfile, prettify=True)
